### PR TITLE
Added support for different swift package manager tools version

### PR DESCRIPTION
**Pull request by tc-sgupta**

### CODE REVIEW

**Comment by tc-sgupta** [comment]
@chriscombs Could you please have a look at this PR

**Review by chriscombs — APPROVED** [review]

**Comment by tc-sgupta** [comment]
@chriscombs Thanks for merging the branch. Could you please create a release.

**Comment by chriscombs** [comment]
Sure thing, done

**Comment by tc-sgupta** [comment]
> Sure thing, done

Thanks very much

**Pull request merged**
