### PR TITLE
Updating Travis

### PR DESCRIPTION
**Pull request by mariusc**
I want to update Travis to use Xcode 8.3 and to also build the example project on the lowest supported target. 

Since I need to actually open a PR to see if this works, this PR is work in progress until further notice, so don't merge it yet

### CODE REVIEW

**Comment by mariusc** [comment]
Ok, so the example project doesn't build :). This is actually one of the main reasons I wanted to make this update, so we can check for that too.

**Comment by dominik-hadl** [comment]
@mariusc Have you verified that this still works with Carthage and it doesn't try to build the example project as well along Serpent? :) Otherwise ready to merge after Travis passes.

**Comment by mariusc** [comment]
@nickskull I'm pretty sure it works fine 
image

**Comment by mariusc** [comment]
Ok, I think this PR is done. Travis now builds using the latest version of Xcode and also builds the example project together with the tests. I think this is ready for review and/or merge

**Review by dominik-hadl — APPROVED** [review]

**Pull request merged**
