### PR TITLE
Feature/embedded property mapping swift4

### PR DESCRIPTION
**Pull request by jakobmygind**
Tested types for now: String, embedded Serializable, Date

Rebased using Marius' Swift4 branch

### CODE REVIEW

**Comment by jakobmygind** [comment]
Unable to merge at until Travis supports new xcode settings

**Comment by dominik-hadl** [comment]
@jakobmygind Try also updating the Travis file, it does support the beta releases.

https://docs.travis-ci.com/user/osx-ci-environment#sts=Xcode version

**Comment by mariusc** [comment]
I'm not sure we should update the `develop` branch to swift 4 yet. Any opinions on this, @nickskull @chriscombs?
This will also conflict with #151, which adds some performance improvements to the swift 3 version

**Comment by dominik-hadl** [comment]
@mariusc I think we should. If need hot fixes for the current version then we branch out from master and port back the changes to develop. There will need to be some work with the other PR to include the changes but let's figure that out a bit later.

**Comment by chriscombs** [comment]
I think we can just merge these changes into the open PR. No reason to have a breaking v2.0 on an old version of Swift.

**Review by chriscombs — APPROVED** [review]

**Pull request merged**
