### PR TITLE
New OS targets

### PR DESCRIPTION
**Pull request by chriscombs**
Added support for tvOS, watchOS, and OSX. 

Part of this required separating _all_ of the HexInitializable code into a separate file, so that it could be excluded from the OSX target

### CODE REVIEW

**Comment by chriscombs** [comment]
@nickskull I'll look into that. You can wait on merging this until then if you want.

**Comment by nickskull** [comment]
@chriscombs Does the color parsing work for OS X as it is right now?

**Comment by dominik-hadl** [comment]
@chriscombs Something like this could make it work

```
#if os(iOS)
import UIKit
typealias Color = UIColor
#elseif os(OSX)
import AppKit
typealias Color = NSColor
#endif
```

**EDIT**: Just verified that it works :)

**Comment by chriscombs** [comment]
That worked better than I expected, no need for the separate file anymore.  Ready to merge

**Comment by chriscombs** [comment]
Hmm, travis doesn't like the schemes. Will sort it out

**Comment by chriscombs** [comment]
Going to try to get it to build all schemes, then will reopen

**Comment by chriscombs** [comment]
I knew that would happen

**Comment by chriscombs** [comment]
Don't want to stay up fighting with YAML anymore, right now it builds iOS, OSX, and tvOS, but not watchOS. Someone needs to add a conditional check to disable "test" on watchOS because unit testing isn't supported for it yet (example here https://github.com/Alamofire/Alamofire/blob/master/.travis.yml).

**Comment by dominik-hadl** [comment]
@chriscombs I'll have a look at this in a few minutes :) Could you force push to this branch and remove all the last testing commits (so that newest commit is 8f05b30)? Also, if you could after that do an interactive `rebase`and squash all the commits in 1-2 that make most sense, that would be great.

**EDIT**: Nevermind, just did it :)

**Comment by dominik-hadl** [comment]
Closing and opening again to trigger travis.

**EDIT**: Looks like force pushes break Travis. Gonna open a new pull request.

**Pull request closed without merging**
